theme: jekyll-theme-minimal
title: Riskgraph.ai
description: Red lights. On time. On line. 
<br>
Keeping trial participants safe, respecting their rights, having data we can trust, making sure the trial is being run as it was meant to be, improving the way the trial is run and preventing problems before they happen.
